/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module sum_pipe_Synth(clk, reset_L, dataA, dataB, sum30_dd);
  wire [3:0] _000_;
  wire [3:0] _001_;
  wire [3:0] _002_;
  wire [3:0] _003_;
  wire [3:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  input clk;
  input [3:0] dataA;
  input [3:0] dataB;
  wire [3:0] data_A_d;
  wire [3:0] data_B_d;
  input reset_L;
  wire [3:0] sum10_d;
  wire [3:0] sum30_d;
  output [3:0] sum30_dd;
  NOT _042_ (
    .A(dataA[0]),
    .Y(_005_)
  );
  NOT _043_ (
    .A(dataB[0]),
    .Y(_006_)
  );
  NOR _044_ (
    .A(_006_),
    .B(_005_),
    .Y(_007_)
  );
  NAND _045_ (
    .A(_006_),
    .B(_005_),
    .Y(_008_)
  );
  NAND _046_ (
    .A(_008_),
    .B(reset_L),
    .Y(_009_)
  );
  NOR _047_ (
    .A(_009_),
    .B(_007_),
    .Y(_002_[0])
  );
  NOT _048_ (
    .A(dataB[1]),
    .Y(_010_)
  );
  NAND _049_ (
    .A(_010_),
    .B(dataA[1]),
    .Y(_011_)
  );
  NOT _050_ (
    .A(dataA[1]),
    .Y(_012_)
  );
  NAND _051_ (
    .A(dataB[1]),
    .B(_012_),
    .Y(_013_)
  );
  NAND _052_ (
    .A(_013_),
    .B(_011_),
    .Y(_014_)
  );
  NOR _053_ (
    .A(_014_),
    .B(_007_),
    .Y(_015_)
  );
  NAND _054_ (
    .A(_014_),
    .B(_007_),
    .Y(_016_)
  );
  NAND _055_ (
    .A(_016_),
    .B(reset_L),
    .Y(_017_)
  );
  NOR _056_ (
    .A(_017_),
    .B(_015_),
    .Y(_002_[1])
  );
  NOT _057_ (
    .A(reset_L),
    .Y(_018_)
  );
  NOT _058_ (
    .A(sum30_d[0]),
    .Y(_019_)
  );
  NOR _059_ (
    .A(_019_),
    .B(_018_),
    .Y(_004_[0])
  );
  NOT _060_ (
    .A(sum30_d[1]),
    .Y(_020_)
  );
  NOR _061_ (
    .A(_020_),
    .B(_018_),
    .Y(_004_[1])
  );
  NOT _062_ (
    .A(sum30_d[2]),
    .Y(_021_)
  );
  NOR _063_ (
    .A(_021_),
    .B(_018_),
    .Y(_004_[2])
  );
  NOT _064_ (
    .A(sum30_d[3]),
    .Y(_022_)
  );
  NOR _065_ (
    .A(_022_),
    .B(_018_),
    .Y(_004_[3])
  );
  NOT _066_ (
    .A(data_A_d[2]),
    .Y(_023_)
  );
  NOT _067_ (
    .A(data_B_d[2]),
    .Y(_024_)
  );
  NOR _068_ (
    .A(_024_),
    .B(_023_),
    .Y(_025_)
  );
  NAND _069_ (
    .A(_024_),
    .B(_023_),
    .Y(_026_)
  );
  NAND _070_ (
    .A(_026_),
    .B(reset_L),
    .Y(_027_)
  );
  NOR _071_ (
    .A(_027_),
    .B(_025_),
    .Y(_003_[2])
  );
  NOT _072_ (
    .A(data_B_d[3]),
    .Y(_028_)
  );
  NAND _073_ (
    .A(_028_),
    .B(data_A_d[3]),
    .Y(_029_)
  );
  NOT _074_ (
    .A(data_A_d[3]),
    .Y(_030_)
  );
  NAND _075_ (
    .A(data_B_d[3]),
    .B(_030_),
    .Y(_031_)
  );
  NAND _076_ (
    .A(_031_),
    .B(_029_),
    .Y(_032_)
  );
  NOR _077_ (
    .A(_032_),
    .B(_025_),
    .Y(_033_)
  );
  NAND _078_ (
    .A(_032_),
    .B(_025_),
    .Y(_034_)
  );
  NAND _079_ (
    .A(_034_),
    .B(reset_L),
    .Y(_035_)
  );
  NOR _080_ (
    .A(_035_),
    .B(_033_),
    .Y(_003_[3])
  );
  NOT _081_ (
    .A(sum10_d[0]),
    .Y(_036_)
  );
  NOR _082_ (
    .A(_036_),
    .B(_018_),
    .Y(_003_[0])
  );
  NOT _083_ (
    .A(sum10_d[1]),
    .Y(_037_)
  );
  NOR _084_ (
    .A(_037_),
    .B(_018_),
    .Y(_003_[1])
  );
  NOT _085_ (
    .A(dataB[2]),
    .Y(_038_)
  );
  NOR _086_ (
    .A(_038_),
    .B(_018_),
    .Y(_001_[2])
  );
  NOT _087_ (
    .A(dataB[3]),
    .Y(_039_)
  );
  NOR _088_ (
    .A(_039_),
    .B(_018_),
    .Y(_001_[3])
  );
  NOT _089_ (
    .A(dataA[2]),
    .Y(_040_)
  );
  NOR _090_ (
    .A(_040_),
    .B(_018_),
    .Y(_000_[2])
  );
  NOT _091_ (
    .A(dataA[3]),
    .Y(_041_)
  );
  NOR _092_ (
    .A(_041_),
    .B(_018_),
    .Y(_000_[3])
  );
  DFF _093_ (
    .C(clk),
    .D(_004_[0]),
    .Q(sum30_dd[0])
  );
  DFF _094_ (
    .C(clk),
    .D(_004_[1]),
    .Q(sum30_dd[1])
  );
  DFF _095_ (
    .C(clk),
    .D(_004_[2]),
    .Q(sum30_dd[2])
  );
  DFF _096_ (
    .C(clk),
    .D(_004_[3]),
    .Q(sum30_dd[3])
  );
  DFF _097_ (
    .C(clk),
    .D(_002_[0]),
    .Q(sum10_d[0])
  );
  DFF _098_ (
    .C(clk),
    .D(_002_[1]),
    .Q(sum10_d[1])
  );
  DFF _099_ (
    .C(clk),
    .D(_003_[0]),
    .Q(sum30_d[0])
  );
  DFF _100_ (
    .C(clk),
    .D(_003_[1]),
    .Q(sum30_d[1])
  );
  DFF _101_ (
    .C(clk),
    .D(_003_[2]),
    .Q(sum30_d[2])
  );
  DFF _102_ (
    .C(clk),
    .D(_003_[3]),
    .Q(sum30_d[3])
  );
  DFF _103_ (
    .C(clk),
    .D(_000_[2]),
    .Q(data_A_d[2])
  );
  DFF _104_ (
    .C(clk),
    .D(_000_[3]),
    .Q(data_A_d[3])
  );
  DFF _105_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_B_d[2])
  );
  DFF _106_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_B_d[3])
  );
  assign sum10_d[3:2] = 2'b00;
endmodule

module sumador_Synth(clk, reset_L, idx, dataA, dataB, sum30_dd, idx_dd);
  input clk;
  input [3:0] dataA;
  input [3:0] dataB;
  input [3:0] idx;
  wire [3:0] idx_d;
  output [3:0] idx_dd;
  input reset_L;
  output [3:0] sum30_dd;
  wire [3:0] sum30_dd_in;
  DFF _0_ (
    .C(clk),
    .D(idx_d[0]),
    .Q(idx_dd[0])
  );
  DFF _1_ (
    .C(clk),
    .D(idx_d[1]),
    .Q(idx_dd[1])
  );
  DFF _2_ (
    .C(clk),
    .D(idx_d[2]),
    .Q(idx_dd[2])
  );
  DFF _3_ (
    .C(clk),
    .D(idx_d[3]),
    .Q(idx_dd[3])
  );
  DFF _4_ (
    .C(clk),
    .D(idx[0]),
    .Q(idx_d[0])
  );
  DFF _5_ (
    .C(clk),
    .D(idx[1]),
    .Q(idx_d[1])
  );
  DFF _6_ (
    .C(clk),
    .D(idx[2]),
    .Q(idx_d[2])
  );
  DFF _7_ (
    .C(clk),
    .D(idx[3]),
    .Q(idx_d[3])
  );
  sum_pipe_Synth pipeline (
    .clk(clk),
    .dataA(dataA),
    .dataB(dataB),
    .reset_L(reset_L),
    .sum30_dd(sum30_dd_in)
  );
  assign sum30_dd = sum30_dd_in;
endmodule
